---
title: Kristian Kim
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
  works:
    title: Works
    output: true
defaults:
- scope:
    path: ''
    type: works
  values:
    metadata: Featured Image
email: hello@kristiankim.com
description: Hi, I'm Kristian Kim. I love designing digital products that make people's
  lives easier and more fun.
baseurl: 
url: http://kristiankim.com
sources:
- _assets/script
- _assets/css
- _assets/fonts
- _assets/images
twitter_username: kristiankim
github_username: kristiankim
markdown: kramdown
permalink: pretty
kramdown:
  auto_ids: false
gems:
- jekyll-feed
- bourbon
- neat
- octopress-autoprefixer
- jekyll-assets
exclude:
- Gemfile
- Gemfile.lock
owner:
  name: Kristian Kim
  avatar: avatar.png
  email: hello@kristiankim.com
  twitter: kristiankim
  github: kristiankim
  dribbble: kristiankim
  location: New York, NY
