---
title: Kristian Kim
email: hello@kristiankim.com
description: |
  I'm Kristian Kim. I design user interfaces, websites and apps that are functional and beautiful.
baseurl: ''
url: www.kristiankim.com
twitter_username: kristiankim
github_username: kristiankim
markdown: kramdown
theme: minima
gems:
- jekyll-feed
- bourbon
- neat
- octopress-autoprefixer
exclude:
- Gemfile
- Gemfile.lock
timezone: America/New_York
